name: main
run-name: main-pipeline
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    container:
      image: node:16
      env:
        NODE_ENV: development
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run test
  build-image:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build image
        run: docker build -t app:latest .
      - name: create a lovely package
        run: docker save app:latest | gzip > lovely_artefact.tar.gz
      - name: XD
        run: ls
      
#1. run unit tests -- automatic
#2. run performance tests -- automatic 
#3. deploy -- run on dispatch
